#STRIPE Information And Security Contact

UR = 'https://shop.littlefeetdenver.com'
KM = '/my-account/'
KD = 'add-payment-method/'
TZ = 'https://api.stripe.com/v1/payment_methods'
LD = '/wp-admin/admin-ajax.php'
KU = 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36'
KR = 'Register'
IP = 'api.stripe.com'
JS = 'application/json'
FK = 'no-cache'
IA = 'application/x-www-form-urlencoded'
HX = 'https://js.stripe.com'
HK = '/'
HW = 'no-cache'
CH = '"Chromium";v="137", "Not/A)Brand";v="24"'
FZ = '?1'
AZ = '"Android"'
MZ = 'empty'
CZ = 'cors'
OZ = 'same-site'
EL = 'document'
LQ = 'navigate'
LI = 'same-origin'
LF = '1'
JK = 'create_and_confirm_setup_intent'
JU = 'wc_stripe_create_and_confirm_setup_intent'
LX = 'Your card was declined.'
RD = 'success'
RX = 'Success'
NS = 'Approved'
LZ = 'Your card number is incorrect.'
LT = 'stripe.js%2F53a74093af%3B+stripe-js-v3%2F53a74093af%3B+payment-element%3B+deferred-intent'